# GitHub Pages deployment disabled per user request
# This workflow has been disabled to prevent automatic deployment to GitHub Pages

name: Deploy Marketing Planner to GitHub Pages (DISABLED)

on:
  # Disabled all triggers
  # push:
  #   branches: [ main, master ]
  # workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: false  # This job will never run
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build app
        run: |
          npm run build
          cp ./dist/index.html ./dist/404.html
        env:
          NODE_ENV: production
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4